project:
  type: book

book:
  title: "R for Longitudinal Data Analysis"
  author: "Liam Wright"
  date: "1/26/2026"
  chapters:
    - 00_preface.qmd
    - 01_introduction_course.qmd
    - 01_introduction_tidyverse.qmd
    - 99_backmatter_references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source

